version: '3.8'

services:
  service:
    container_name: hyunseoki_GenerativeModels
    build:
      context: $PWD
      args:
        - USER
        - XDG_RUNTIME_DIR
    image: hyunseoki/generativemodels
    tty: true
    stdin_open: true
    shm_size: 1TB
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
    volumes:
      - $PWD:/workspace
      - /mnt/nas206/ANO_DET/:/workspace/datasets/ANO_DET
